apiVersion: apps/v1
kind: Deployment
metadata:
  name: polygon-stock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polygon-stock
  template:
    metadata:
      labels:
        app: polygon-stock
    spec:
      imagePullSecrets:
        - name: harbor-registry
      containers:
        - name: polygon-stock
          image: "registry.goboolean.io/fetch-system/worker:prod-latest"
          imagePullPolicy: Always
          env:
            - name: POLYGON_SECRET_KEY
              value: ""
            - name: PLATFORM
              value: "POLYGON"
            - name: MARKET
              value: "STOCK"
