apiVersion: apps/v1
kind: Deployment
metadata:
  name: polygon-stock
  namespace: fetch-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polygon-stock
  template:
    metadata:
      labels:
        app: polygon-stock
    spec:
      containers:
        - name: polygon-stock
          image: "registry.goboolean.io/fetch-system/worker:prod-latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: POLYGON_SECRET_KEY
              value: ""
            - name: PLATFORM
              value: "POLYGON"
            - name: MARKET
              value: "STOCK"
            - name: ETCD_HOST
              value: "etcd.etcd.svc.cluster.local:2379"
            - name: KAFKA_BOOTSTRAP_HOST
              value: "kafka.kafka.svc.cluster.local:9092"
            - name: OTEL_ENDPOINT
              value: "otel-collector.fetch-system.svc.cluster.local:4317"
            - name: WORKER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
