apiVersion: apps/v1
kind: Deployment
metadata:
  name: polygon-proxy
  namespace: fetch-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polygon-proxy
  template:
    metadata:
      labels:
        app: polygon-proxy
    spec:
      containers:
        - name: polygon-proxy
          image: ""
          ports:
            - containerPort: 8080
