apiVersion: v1
kind: Service
metadata:
  name: polygon-proxy
  namespace: fetch-system
spec:
  selector:
    app: polygon-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
