apiVersion: v1
kind: Service
metadata:
  name: fetch-system-polygon-proxy
spec:
  selector:
    app: fetch-system-polygon-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
