apiVersion: apps/v1
kind: Deployment
metadata:
  name: polygon-proxy
  namespace: fetch-system
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: load-tester-sa
      containers:
        - name: polygon-proxy
          image: google/cloud-sdk:alpine
          command: ["/bin/sh", "-c"]
          args:
            - |
              /scripts/init.sh
          volumeMounts:
            - name: init-script-volume
              mountPath: /scripts
          ports:
            - containerPort: 9000
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "nc -z localhost 9000 || exit 1"
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 10
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: nginx-conf-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          ports:
            - containerPort: 8080
      volumes:
        - name: init-script-volume
          configMap:
            name: polygon-proxy-init-script
            defaultMode: 0744
        - name: nginx-conf-volume
          configMap:
            name: polygon-proxy-nginx-conf
            defaultMode: 0644
