apiVersion: v1
kind: ConfigMap
metadata:
  name: polygon-proxy-init-script
  namespace: fetch-system
data:
  init.sh: |
    #!/bin/sh

    gcloud config set core/project goboolean-450909

    apk add --no-cache curl

    curl -Ls https://github.com/vi/websocat/releases/latest/download/websocat.x86_64-unknown-linux-musl -o /usr/local/bin/websocat
    chmod +x /usr/local/bin/websocat

    gsutil ls gs://goboolean-450909-load-test
    gsutil cp gs://goboolean-450909-load-test/output.txt /data/output.txt

    websocat --binary ws-listen:0.0.0.0:8080 sh-c:'cat /data/output.txt'
