apiVersion: v1
kind: ConfigMap
metadata:
  name: polygon-proxy-nginx-conf
  namespace: fetch-system
data:
  nginx.conf: |
    events {
        worker_connections 4;
    }
    http {
        server {
            listen 8080;
            location / {
                proxy_pass http://localhost:9000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
                limit_rate 128;
                limit_rate_after 0;
            }
        }
    }
