apiVersion: v1
kind: ConfigMap
metadata:
  name: polygon-proxy-nginx-conf
  namespace: fetch-system
data:
  nginx.conf: |
    events {
        worker_connections 4;
    }
    stream {
        server {
            listen 8080;
            proxy_pass http://localhost:9000;
            limit_rate 256;
        }
    }
