apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetch-system-streams
  annotations:
    avp.kubernetes.io/path: "kv-v2/data/application/fetch-system/streams"
spec:
  template:
    spec:
      containers:
        - name: fetch-system-streams
          image: "34.64.83.183:80/fetch-system/streams:79058dc"
          env:
            - name: KAFKA_BOOTSTRAP_HOST
              value: <KAFKA_BOOTSTRAP_HOST>
            - name: ETCD_HOST
              value: <ETCD_HOST>
            - name: OTEL_ENDPOINT
              value: <OTEL_ENDPOINT>
