apiVersion: apps/v1
kind: Deployment
metadata:
  name: streams
  namespace: fetch-system
  annotations:
    avp.kubernetes.io/path: "kv/data/application/fetch-system/streams"
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: streams
          image: "registry.goboolean.io/fetch-system/streams:72df580"
          resources: {}
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: <KAFKA_BOOTSTRAP_SERVERS>
            - name: ETCD_ENDPOINTS
              value: <ETCD_ENDPOINTS>
            - name: OTEL_ENDPOINT
              value: <OTEL_ENDPOINT>
