apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetch-system-streams
  annotations:
    avp.kubernetes.io/path: "kv-v2/data/application/fetch-system/streams"
spec:
  template:
    spec:
      containers:
        - name: fetch-system-streams
          image: "registry.goboolean.io/fetch-system/streams:345f45c"
          resources:
            requests:
              cpu: 2000m
              memory: 2Gi
            limits:
              cpu: 4000m
              memory: 4Gi
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: <KAFKA_BOOTSTRAP_SERVERS>
            - name: ETCD_ENDPOINTS
              value: <ETCD_ENDPOINTS>
            - name: OTEL_ENDPOINT
              value: <OTEL_ENDPOINT>
