apiVersion: apps/v1
kind: Deployment
metadata:
  name: streams
  namespace: fetch-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streams
  template:
    metadata:
      labels:
        app: streams
    spec:
      containers:
        - name: streams
          image: "registry.goboolean.io/fetch-system/streams:prod-latest"
          imagePullPolicy: Always
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: ""
            - name: ETCD_ENDPOINTS
              value: ""
            - name: OTEL_ENDPOINT
              value: ""
