apiVersion: batch/v1
kind: Job
metadata:
  name: "fetch-system-preparer"
  annotations:
    avp.kubernetes.io/path: "kv-v2/data/application/fetch-system/util/preparer"
spec:
  template:
    metadata:
      name: "fetch-system-preparer"
    spec:
      containers:
        - name: preparer
          image: "registry.goboolean.io/fetch-system/util/preparer:edbf3b9"
          env:
            - name: POSTGRES_HOST
              value: <POSTGRES_HOST>
            - name: POSTGRES_PORT
              value: <POSTGRES_PORT>
            - name: POSTGRES_USER
              value: <POSTGRES_USER>
            - name: POSTGRES_PASSWORD
              value: <POSTGRES_PASSWORD>
            - name: POSTGRES_DATABASE
              value: <POSTGRES_DATABASE>
            - name: ETCD_HOST
              value: <ETCD_HOST>
            - name: KAFKA_CONNECT_HOST
              value: <KAFKA_CONNECT_HOST>
            - name: KAFKA_BOOTSTRAP_HOST
              value: <KAFKA_BOOTSTRAP_HOST>
            - name: POLYGON_SECRET_KEY
              value: <POLYGON_SECRET_KEY>
            - name: INFLUXDB_URL
              value: <INFLUXDB_URL>
            - name: INFLUXDB_TOKEN
              value: <INFLUXDB_TOKEN>
            - name: INFLUXDB_ORGANIZATION
              value: <INFLUXDB_ORGANIZATION>
