apiVersion: apps/v1
kind: Deployment
metadata:
  name: kis-stock
  annotations:
    avp.kubernetes.io/path: "kv-v2/data/application/fetch-system/worker/kis-stock"
spec:
  replicas: 0
  template:
    spec:
      containers:
        - name: kis-stock
          image: "registry.goboolean.io/fetch-system/worker:9025b36"
          env:
            - name: KIS_APP_KEY
              value: <KIS_APP_KEY>
            - name: KIS_SECRET_KEY
              value: <KIS_SECRET_KEY>
            - name: PLATFORM
              value: <PLATFORM>
            - name: MARKET
              value: <MARKET>
            - name: ETCD_HOST
              value: <ETCD_HOST>
            - name: KAFKA_BOOTSTRAP_HOST
              value: <KAFKA_BOOTSTRAP_HOST>
            - name: OTEL_ENDPOINT
              value: <OTEL_ENDPOINT>
            - name: WORKER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
