apiVersion: apps/v1
kind: Deployment
metadata:
  name: polygon-stock
  annotations:
    avp.kubernetes.io/path: "kv/data/application/fetch-system/worker/polygon-stock"
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: polygon-stock
          image: "registry.goboolean.io/fetch-system/worker:f397bf7"
          env:
            - name: POLYGON_SECRET_KEY
              value: <POLYGON_SECRET_KEY>
            - name: PLATFORM
              value: <PLATFORM>
            - name: MARKET
              value: <MARKET>
            - name: ETCD_HOST
              value: <ETCD_HOST>
            - name: KAFKA_BOOTSTRAP_HOST
              value: <KAFKA_BOOTSTRAP_HOST>
            - name: OTEL_ENDPOINT
              value: <OTEL_ENDPOINT>
            - name: WORKER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
