name: "Update image tag"
description: "Update image tag of kustomize manifest"
inputs:
  app-name:
    description: "Application name"
    required: true
  image-name:
    description: "Image name"
    required: true
  image-tag:
    description: "Image tag"
    required: true
  github-token:
    description: "Github token with repo access"
    required: true
  profile:
    description: "Profile"
    required: true
  pull-request-link:
    description: "Pull request link"
    required: false
runs:
  using: "composite"
  steps:
    - name: "Checkout main branch of manifests repository"
      uses: actions/checkout@v2
      with:
        token: ${{ inputs.github-token }}
        repository: goboolean/manifests
        ref: main

    - name: "Update image tag and commit"
      shell: bash
      run: |
        chmod +x .github/actions/update-image-tag/update_image_tag.sh
        ./.github/actions/update-image-tag/update_image_tag.sh -a ${{ inputs.app-name }} -i ${{ inputs.image-name }} -t ${{ inputs.image-tag }} -p ${{ inputs.profile }}
        git config user.name goboolean-io
        git config user.email goboolean.io@gmail.com
        git add .
        git commit -m "CI: update ${{ inputs.app-name }} image (${{ inputs.image-name }}) to tag ${{ inputs.image-tag }} in profile ${{ inputs.profile }}"  

    - name: "Create Pull request and merge"
      uses: peter-evans/create-pull-request@v7
      id: pull-request
      with:
        token: ${{ inputs.github-token }}
        title: "CI: update ${{ inputs.app-name }} image (${{ inputs.image-name }}) to tag ${{ inputs.image-tag }} in profile ${{ inputs.profile }}"
        body: |
          This PR updates ${{ inputs.app-name }} image (${{ inputs.image-name }}) to tag ${{ inputs.image-tag }} in profile ${{ inputs.profile }}
          ${{ inputs.pull-request-link && format('Pull request link: {0}', inputs.pull-request-link) }}
        branch-suffix: random
        delete-branch: true

    - name: "Merge pull request"
      if: steps.pull-request.outputs.pull-request-operation == 'created'
      shell: bash
      run: gh pr merge ${{ steps.pull-request.outputs.pull-request-number }} --squash --auto --delete-branch --repo goboolean/manifests
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
